// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCocB6IDNnD4OeyB-WI9wz8JzKOmlHIZQ0',
    appId: '1:566870094896:web:82449ed6e843fd206129f5',
    messagingSenderId: '566870094896',
    projectId: 'flutter-app-auth-97a06',
    authDomain: 'flutter-app-auth-97a06.firebaseapp.com',
    storageBucket: 'flutter-app-auth-97a06.firebasestorage.app',
    measurementId: 'G-7XBYCVZF04',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfNZb88uG-44PlTeIjjCWhbMG38p205h8',
    appId: '1:566870094896:android:eec06162d493921a6129f5',
    messagingSenderId: '566870094896',
    projectId: 'flutter-app-auth-97a06',
    storageBucket: 'flutter-app-auth-97a06.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByVmumFKr1azP6hctGdJoqLUUEoPJo24g',
    appId: '1:566870094896:ios:8169426d1bd41fc56129f5',
    messagingSenderId: '566870094896',
    projectId: 'flutter-app-auth-97a06',
    storageBucket: 'flutter-app-auth-97a06.firebasestorage.app',
    iosBundleId: 'com.example.firebaseIntegrationProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByVmumFKr1azP6hctGdJoqLUUEoPJo24g',
    appId: '1:566870094896:ios:8169426d1bd41fc56129f5',
    messagingSenderId: '566870094896',
    projectId: 'flutter-app-auth-97a06',
    storageBucket: 'flutter-app-auth-97a06.firebasestorage.app',
    iosBundleId: 'com.example.firebaseIntegrationProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCocB6IDNnD4OeyB-WI9wz8JzKOmlHIZQ0',
    appId: '1:566870094896:web:5a93aec187d8ec8b6129f5',
    messagingSenderId: '566870094896',
    projectId: 'flutter-app-auth-97a06',
    authDomain: 'flutter-app-auth-97a06.firebaseapp.com',
    storageBucket: 'flutter-app-auth-97a06.firebasestorage.app',
    measurementId: 'G-9N4DBH4GPW',
  );
}
